name: Count Lines of Code

on:
  push:
    branches:
      - main
jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install cloc
        run: sudo apt-get install -y cloc
      - name: Count lines of code
        id: cloc
        run: |
          cloc . > cloc.txt
      - name: Add cloc output to summary
        run: |
          echo "```txt" >> $GITHUB_STEP_SUMMARY
          cat cloc.txt >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
